### ISSUE TITLE
Problem building on Ubuntu 15.10

### ISSUE THREAD

**Issue by dmr** [otalk/restund#11]
When I run make I get the following message:

```
$ make

  CC      build-x86_64/src/db.o
src/db.c:214:32: warning: ‘struct timespec’ declared inside parameter list
 static void gettimespec(struct timespec *ts, uint32_t offset)
                                ^
src/db.c: In function ‘gettimespec’:
src/db.c:220:4: error: dereferencing pointer to incomplete type ‘struct timespec’
  ts->tv_sec  = tv.tv_sec + offset;
    ^
src/db.c: In function ‘database_thread’:
src/db.c:227:18: error: storage size of ‘ts’ isn’t known
  struct timespec ts;
                  ^
src/db.c:227:18: warning: unused variable ‘ts’ [-Wunused-variable]
Makefile:108: recipe for target 'build-x86_64/src/db.o' failed
make: *** [build-x86_64/src/db.o] Error 1
```

Am I missing something?

**Comment by dmr** [comment]
I fixed the compile problem:

```
diff --git a/src/db.c b/src/db.c
index f472224..193a221 100644
--- a/src/db.c
+++ b/src/db.c
@@ -209,6 +209,12 @@ static int save_traffic_records(void)
 }
 
 
+struct timespec {
+       int tv_sec;
+       float tv_usec;
+       float tv_nsec;
+};
+
 static void gettimespec(struct timespec *ts, uint32_t offset)
 {
        struct timeval tv;
```

Not sure about the datatypes though :)

**Comment by nonchip** [comment]
you're missing the standard spec (`-std=gnu99`).

see also: http://stackoverflow.com/questions/3875197/linux-gcc-with-std-c99-complains-about-not-knowing-struct-timespec

**Comment by daveime** [comment]
Anyone arriving here from Google, please be aware you still have to patch the Makefile manually if you got the source from the official repository at http://www.creytiv.com/pub.

The latest 	restund-0.4.12.tar.gz on the official repository is dated October 2015, but this issue was only "closed" July 2016, and the fix has never made it.

So edit the Makefile and change the line from

CFLAGS	+= -I$(LIBRE_INC) -Iinclude

to

CFLAGS	+= -I$(LIBRE_INC) -Iinclude -std=gnu99

After that, you'll get a clean compile, verified on Ubuntu 16.04.

**Comment by fippo** [comment]
I think you can just use the stock version from creytiv these days, the time-limited credentials stuff is available there (in a slightly different implementation)

**Comment by daveime** [comment]
It's only because I happened to be building re-0.5.3 and restund-0.4.12 this afternoon that I came across this issue. They do seem to be the latest source versions in the pub directory, and the compile errors do still appear on a standard Ubuntu 16.04 AWS shard unless this patch to Makefile is done.

Anyway, if it helps some future Googler out, all to the good.

**Comment by jr2wolfgang** [comment]
Thanks @daveime ! You save my life! I almost gave up but your solution works for me. I am using Ubuntu 16 that's why I'm having this issue. Anyways, all good now
